[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
base = "https://mainnet.base.org"
optimism = "https://mainnet.optimism.io"
anvil = "http://127.0.0.1:8545"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }
optimism = { key = "${ETHERSCAN_API_KEY}" }
